In [1]:
import numpy as np

In [2]:
abc = np.random.randint(1,10,size=20)

In [3]:
abc

array([6, 8, 1, 5, 3, 9, 2, 7, 5, 7, 9, 7, 3, 1, 9, 4, 2, 2, 5, 3])

In [4]:
abc[abc > 5]

array([6, 8, 9, 7, 7, 9, 7, 9])

In [7]:
[abc > 5]

[array([ True,  True, False, False, False,  True, False,  True, False,
         True,  True,  True, False, False,  True, False, False, False,
        False, False])]

In [11]:
np.where(abc > 5)

(array([ 0,  1,  5,  7,  9, 10, 11, 14], dtype=int64),)

In [13]:
np.where(abc > 5 , "yes", "No")

array(['yes', 'yes', 'No', 'No', 'No', 'yes', 'No', 'yes', 'No', 'yes',
       'yes', 'yes', 'No', 'No', 'yes', 'No', 'No', 'No', 'No', 'No'],
      dtype='<U3')

In [15]:
import pandas as pd

# Pandas

In [16]:
import numpy as np

In [18]:
s1 =  pd.Series()

<ipython-input-18-8eedfb7d96dd>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s1 =  pd.Series()


In [19]:
type(s1)

pandas.core.series.Series

In [20]:
s2 = pd.Series([1,2,3])

In [21]:
print(s2)

0    1
1    2
2    3
dtype: int64


In [25]:
s3= pd.Series(["a","b","C"])

In [26]:
print(s3)

0    a
1    b
2    C
dtype: object


In [27]:
s4 = pd.Series(np.random.randint(1,10,15))

In [28]:
print(s4)

0     3
1     4
2     2
3     1
4     6
5     6
6     6
7     8
8     5
9     2
10    8
11    9
12    1
13    4
14    2
dtype: int32


In [29]:
type(s4)

pandas.core.series.Series

In [30]:
s5 = pd.Series(np.random.randint(1,10,5), index=['A','B','C','D','E'])

In [31]:
print(s5)

A    3
B    2
C    2
D    5
E    2
dtype: int32


In [32]:
d1= {"mango":240, "Guava":500, "Plum": 200, "Orange": 120}

In [33]:
s6 = pd.Series(d1)

In [34]:
print(s6)

mango     240
Guava     500
Plum      200
Orange    120
dtype: int64


In [36]:
s4

0     3
1     4
2     2
3     1
4     6
5     6
6     6
7     8
8     5
9     2
10    8
11    9
12    1
13    4
14    2
dtype: int32

In [38]:
s4[4]

6

In [39]:
s4[3:11]

3     1
4     6
5     6
6     6
7     8
8     5
9     2
10    8
dtype: int32

In [40]:
s2

0    1
1    2
2    3
dtype: int64

In [41]:
s2[1] = 199

In [42]:
s2

0      1
1    199
2      3
dtype: int64

In [43]:
s5

A    3
B    2
C    2
D    5
E    2
dtype: int32

In [44]:
s5 * 4

A    12
B     8
C     8
D    20
E     8
dtype: int32

In [45]:
s5 * s5

A     9
B     4
C     4
D    25
E     4
dtype: int32

# Pandas DataFrame

In [57]:
df1 = { "A": [1,2,3,4], "B":[4,5,6,7]}

SyntaxError: invalid syntax (<ipython-input-57-ef279a1848a7>, line 1)

In [47]:
print(df1)

{'A': [1, 2, 3, 4], 'B': [4, 5, 6, 7]}


In [60]:
df7 = {"A": np.random.randn(10), "B": np.random.randn(10)}

In [61]:
df7

{'A': array([ 0.32236481,  0.84348921, -0.16670235,  0.98633223, -0.41278087,
        -0.67786873, -0.31760111, -0.66875287, -1.47940866,  1.62324348]),
 'B': array([ 1.48212855, -0.56138949,  0.18568091,  0.12116923,  0.4305213 ,
         0.68849139, -1.28849258, -0.99039415, -0.41018576, -0.16503691])}

In [62]:
df8=pd.DataFrame(df7)

In [63]:
df8

A         B
0  0.322365  1.482129
1  0.843489 -0.561389
2 -0.166702  0.185681
3  0.986332  0.121169
4 -0.412781  0.430521
5 -0.677869  0.688491
6 -0.317601 -1.288493
7 -0.668753 -0.990394
8 -1.479409 -0.410186
9  1.623243 -0.165037

In [64]:
df8.mean()

A    0.005232
B   -0.050751
dtype: float64

In [65]:
df8.std()

A    0.931983
B    0.818618
dtype: float64

In [66]:
df8.head(3)

A         B
0  0.322365  1.482129
1  0.843489 -0.561389
2 -0.166702  0.185681

In [67]:
df8.head(5)

A         B
0  0.322365  1.482129
1  0.843489 -0.561389
2 -0.166702  0.185681
3  0.986332  0.121169
4 -0.412781  0.430521

In [68]:
df8.tail(3)

A         B
7 -0.668753 -0.990394
8 -1.479409 -0.410186
9  1.623243 -0.165037

In [70]:
df8.index

RangeIndex(start=0, stop=10, step=1)

In [71]:
df8.values

array([[ 0.32236481,  1.48212855],
       [ 0.84348921, -0.56138949],
       [-0.16670235,  0.18568091],
       [ 0.98633223,  0.12116923],
       [-0.41278087,  0.4305213 ],
       [-0.67786873,  0.68849139],
       [-0.31760111, -1.28849258],
       [-0.66875287, -0.99039415],
       [-1.47940866, -0.41018576],
       [ 1.62324348, -0.16503691]])

In [72]:
df8.columns

Index(['A', 'B'], dtype='object')

In [73]:
df8

A         B
0  0.322365  1.482129
1  0.843489 -0.561389
2 -0.166702  0.185681
3  0.986332  0.121169
4 -0.412781  0.430521
5 -0.677869  0.688491
6 -0.317601 -1.288493
7 -0.668753 -0.990394
8 -1.479409 -0.410186
9  1.623243 -0.165037

# importing a csv, or excel sheet in to python

In [88]:
import sys

In [89]:
sys.path.append('C:/Users/pyari/Desktop/')

In [90]:
df10 = pd.read_csv('crop.csv')

In [91]:
print(df10)

    Year  rice  wheat  Maize  pulses
0   1980   101    201    301     401
1   1981   102    202    302     402
2   1982   103    203    303     403
3   1983   104    204    304     404
4   1984   105    205    305     405
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416
16  1996   117    217    317     417
17  1997   118    218    318     418
18  1998   119    219    319     419
19  1999   120    220    320     420
20  2000   121    221    321     421


In [94]:
df11 = pd.read_csv('crop.csv',usecols=[0,3,4],nrows=10)

In [95]:
df11

Year  Maize  pulses
0  1980    301     401
1  1981    302     402
2  1982    303     403
3  1983    304     404
4  1984    305     405
5  1985    306     406
6  1986    307     407
7  1987    308     408
8  1988    309     409
9  1989    310     410

In [97]:
df12 =pd.read_excel('crop.xlsx',sheet_name="test")

In [98]:
df12

Year  rice  wheat  Maize  pulses
0   1980   101    201    301     401
1   1981   102    202    302     402
2   1982   103    203    303     403
3   1983   104    204    304     404
4   1984   105    205    305     405
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416
16  1996   117    217    317     417
17  1997   118    218    318     418
18  1998   119    219    319     419
19  1999   120    220    320     420
20  2000   121    221    321     421

In [100]:
df10

Year  rice  wheat  Maize  pulses
0   1980   101    201    301     401
1   1981   102    202    302     402
2   1982   103    203    303     403
3   1983   104    204    304     404
4   1984   105    205    305     405
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416
16  1996   117    217    317     417
17  1997   118    218    318     418
18  1998   119    219    319     419
19  1999   120    220    320     420
20  2000   121    221    321     421

In [102]:
df13 = df10["rice"]

In [103]:
df13

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
15    116
16    117
17    118
18    119
19    120
20    121
Name: rice, dtype: int64

In [104]:
sum(df13)

2331

In [105]:
df10

Year  rice  wheat  Maize  pulses
0   1980   101    201    301     401
1   1981   102    202    302     402
2   1982   103    203    303     403
3   1983   104    204    304     404
4   1984   105    205    305     405
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416
16  1996   117    217    317     417
17  1997   118    218    318     418
18  1998   119    219    319     419
19  1999   120    220    320     420
20  2000   121    221    321     421

In [106]:
df10.head()

Year  rice  wheat  Maize  pulses
0  1980   101    201    301     401
1  1981   102    202    302     402
2  1982   103    203    303     403
3  1983   104    204    304     404
4  1984   105    205    305     405

In [107]:
df14 = df10 [["rice","Maize"]]

In [108]:
df14

rice  Maize
0    101    301
1    102    302
2    103    303
3    104    304
4    105    305
5    106    306
6    107    307
7    108    308
8    109    309
9    110    310
10   111    311
11   112    312
12   113    313
13   114    314
14   115    315
15   116    316
16   117    317
17   118    318
18   119    319
19   120    320
20   121    321

In [109]:
df10

Year  rice  wheat  Maize  pulses
0   1980   101    201    301     401
1   1981   102    202    302     402
2   1982   103    203    303     403
3   1983   104    204    304     404
4   1984   105    205    305     405
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416
16  1996   117    217    317     417
17  1997   118    218    318     418
18  1998   119    219    319     419
19  1999   120    220    320     420
20  2000   121    221    321     421

In [110]:
df10[5:16]

Year  rice  wheat  Maize  pulses
5   1985   106    206    306     406
6   1986   107    207    307     407
7   1987   108    208    308     408
8   1988   109    209    309     409
9   1989   110    210    310     410
10  1990   111    211    311     411
11  1991   112    212    312     412
12  1992   113    213    313     413
13  1993   114    214    314     414
14  1994   115    215    315     415
15  1995   116    216    316     416

In [120]:
df10[5:16][['rice','wheat']]

rice  wheat
5    106    206
6    107    207
7    108    208
8    109    209
9    110    210
10   111    211
11   112    212
12   113    213
13   114    214
14   115    215
15   116    216