# Array: you can store only one type of dataset

In [12]:
from array import *
numbers = array('i',[1,2,3,4,5])

In [13]:
type(numbers)

array.array

In [14]:
numbers[1]

2

In [15]:
#insert 20 in first position
numbers.insert(0,20)

In [16]:
numbers

array('i', [20, 1, 2, 3, 4, 5])

In [17]:
numbers.pop()

5

In [18]:
numbers

array('i', [20, 1, 2, 3, 4])

In [19]:
numbers.pop(3)

3

In [20]:
numbers

array('i', [20, 1, 2, 4])

In [21]:
numbers.append(6)

In [22]:
numbers

array('i', [20, 1, 2, 4, 6])

# Numpy array -- Numerical python--- arithmatic
#alias

import numpy as np


In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [25]:
list1=[1,2,3]
list2=[4,5,6]

In [26]:
list3=list1+list2

In [27]:
print(list3)

[1, 2, 3, 4, 5, 6]


In [28]:
nparr1=np.array([1,2,3])

In [29]:
nparr2=np.array([4,5,6])

In [30]:
nparr3=nparr1 + nparr2

In [31]:
print(nparr3)

[5 7 9]


In [32]:
num = nparr1 * 5

In [33]:
print(num)

[ 5 10 15]


In [34]:
n=np.array([1,2,3,4,5]) #1D array

In [35]:
n1 =np.array([[1,2,3],[4,5,6]])

In [36]:
print(n)

[1 2 3 4 5]


In [58]:
np.shape(n)

(5,)

In [38]:
print(n1)

[[1 2 3]
 [4 5 6]]


In [39]:
n[2]

3

In [42]:
n1[0]

array([1, 2, 3])

In [43]:
n1[1]

array([4, 5, 6])

In [57]:
n1.shape

(2, 3)

In [44]:
n1[1,1]

5

In [45]:
n1 =np.array([[1,2,3],[4,5,6]])

In [47]:
cities = np.array ([["Delhi","Agra","Chandigarh"],["Madras","Hydrabad","Vizag"]])

In [49]:
cities[1]

array(['Madras', 'Hydrabad', 'Vizag'], dtype='<U10')

In [50]:
cities[1,0]

'Madras'

In [51]:
cities[0,0]

'Delhi'

In [52]:
m=np.array([2,4,6,0,7,8])

In [53]:
np.sort(m)

array([0, 2, 4, 6, 7, 8])

In [54]:
nm=np.array(['Madras', 'Hydrabad', 'Vizag'])

In [55]:
np.sort(nm)

array(['Hydrabad', 'Madras', 'Vizag'], dtype='<U8')

# creating array using built in functions


In [56]:
#zeros (shape,dtype=float)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [61]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [66]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
#full
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

# arange --- to create a range  arange([start],stop,[inteval])

In [68]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [69]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [70]:
np.arange(3,31,5)

array([ 3,  8, 13, 18, 23, 28])

In [73]:
np.arange(3,8,0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

# use of linespace to create array

In [78]:
#linspace(start,stop,num=...,endpoint=True)
np.linspace(2,8,num=5)

array([2. , 3.5, 5. , 6.5, 8. ])

In [79]:
np.linspace(2,3,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [80]:
np.linspace(11,20,num=10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])