# Numpy

In [2]:
import numpy as np


In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [12]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# linspace

In [14]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(1,10,10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

# random sampling

In [16]:
#rand (random number)
np.random.rand(3)

array([0.44120888, 0.56092666, 0.87975396])

In [17]:
np.random.rand(4)

array([0.35355471, 0.71350327, 0.14750465, 0.46050943])

In [18]:
np.random.rand(2,3)

array([[0.8443522 , 0.46593749, 0.1530033 ],
       [0.9730308 , 0.24112743, 0.83592012]])

In [19]:
#randint (random integer)
np.random.randint(5)

0

In [20]:
np.random.randint(5)

2

In [21]:
np.random.randint(2,8)

7

In [22]:
np.random.randint(2,8)

6

In [23]:
np.random.randint (1,11,size=20)

array([ 9,  4,  6,  3,  2,  6,  7,  1,  3,  9,  5,  1,  6,  1,  2,  9,  1,
        3, 10, 10])

In [24]:
np.random.randint (1,11,size=(4,5))

array([[ 5,  6,  3,  5,  7],
       [ 6,  3,  7,  1,  2],
       [ 7,  2,  2, 10, 10],
       [ 1,  1,  3,  6,  8]])

In [25]:
arr1 = np.random.randint (1,11,size=20)

In [26]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [27]:
arr2 = np.random.randint (1,11,size=(4,5))

In [28]:
arr2 

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [29]:
#checking of dimention of a array using ndim function
arr1.ndim

1

In [30]:
arr2.ndim

2

In [32]:
#checking the shape
arr1.shape

(20,)

In [33]:
arr2.shape

(4, 5)

In [34]:
#total no of elements
arr1.size

20

In [35]:
arr2.size

20

In [36]:
#data type
arr1.dtype

dtype('int32')

In [37]:
arr1,arr2

(array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8]),
 array([[ 2, 10,  6,  3,  8],
        [ 6,  6,  9,  1,  1],
        [ 8,  7,  7,  4,  3],
        [ 2,  5,  8,  2,  8]]))

In [39]:
#mean
arr1.mean()

5.1

In [40]:
arr2.mean()

5.3

In [41]:
arr2.mean(axis=0)

array([4.5, 7. , 7.5, 2.5, 5. ])

In [42]:
arr2.mean(axis=1)

array([5.8, 4.6, 5.8, 5. ])

In [45]:
arr1.max()

9

In [46]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [47]:
arr1.min()

1

In [48]:
#standard deviation
arr1.std()

2.5865034312755126

In [49]:
arr1.var()

6.69

In [50]:
arr2.var(axis=1)

array([8.96, 9.84, 3.76, 7.2 ])

In [51]:
arr2

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [52]:
arr2.var(axis=0)

array([6.75, 3.5 , 1.25, 1.25, 9.5 ])

variance = 7.709999999999998


In [57]:
#addition (sum)

arr2.sum()

106

In [58]:
arr2.sum(axis=0)

array([18, 28, 30, 10, 20])

In [59]:
arr2

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [60]:
arr2.sum(axis=1)

array([29, 23, 29, 25])

In [61]:
arr2

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [62]:
arr2 * 5

array([[10, 50, 30, 15, 40],
       [30, 30, 45,  5,  5],
       [40, 35, 35, 20, 15],
       [10, 25, 40, 10, 40]])

In [63]:
arr1 -4

array([-2,  3,  4,  1,  3,  5,  1, -3, -3,  2,  4,  1,  0,  2, -2, -1,  4,
       -3,  2,  4])

In [64]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [67]:
arr3 = np.random.randint(20,size=20)

In [68]:
arr3

array([12,  8,  2, 19,  4,  7,  2,  3,  9, 13, 15,  1, 12, 19,  4, 18, 13,
        0, 14,  3])

In [69]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [70]:
arr1.shape

(20,)

In [72]:
arr3.shape

(20,)

In [73]:
arr4 = arr1 +arr3

In [74]:
arr4

array([14, 15, 10, 24, 11, 16,  7,  4, 10, 19, 23,  6, 16, 25,  6, 21, 21,
        1, 20, 11])

In [76]:
arr4.shape

(20,)

In [77]:
arr4.size

20

In [75]:
arr5 = ([1,4,9,16,25])

In [78]:
np.sqrt(arr5)

array([1., 2., 3., 4., 5.])

In [79]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

# reshape an array

In [82]:
arr1.shape

(20,)

In [84]:
arr6 = arr1.reshape(2,10)

In [85]:
arr6

array([[2, 7, 8, 5, 7, 9, 5, 1, 1, 6],
       [8, 5, 4, 6, 2, 3, 8, 1, 6, 8]])

In [86]:
arr1.reshape(5,4)

array([[2, 7, 8, 5],
       [7, 9, 5, 1],
       [1, 6, 8, 5],
       [4, 6, 2, 3],
       [8, 1, 6, 8]])

In [87]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [88]:
arr2

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [89]:
arr7 = arr2.reshape (2,10)

In [90]:
arr7

array([[ 2, 10,  6,  3,  8,  6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3,  2,  5,  8,  2,  8]])

In [91]:
arr2.reshape (5,4)

array([[ 2, 10,  6,  3],
       [ 8,  6,  6,  9],
       [ 1,  1,  8,  7],
       [ 7,  4,  3,  2],
       [ 5,  8,  2,  8]])

In [93]:
arr8 = np.random.rand (9)

In [94]:
arr8

array([0.73902748, 0.43169976, 0.07356426, 0.40915793, 0.9208488 ,
       0.76970348, 0.63662987, 0.72932131, 0.15704351])

In [96]:
#rounding
arr8.round(1)

array([0.7, 0.4, 0.1, 0.4, 0.9, 0.8, 0.6, 0.7, 0.2])

In [97]:
np.round(arr8,2)

array([0.74, 0.43, 0.07, 0.41, 0.92, 0.77, 0.64, 0.73, 0.16])

In [98]:
arr8

array([0.73902748, 0.43169976, 0.07356426, 0.40915793, 0.9208488 ,
       0.76970348, 0.63662987, 0.72932131, 0.15704351])

In [99]:
arr1

array([2, 7, 8, 5, 7, 9, 5, 1, 1, 6, 8, 5, 4, 6, 2, 3, 8, 1, 6, 8])

In [100]:
np.sort(arr1)

array([1, 1, 1, 2, 2, 3, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9])

In [101]:
arr1.sort()

In [102]:
arr1

array([1, 1, 1, 2, 2, 3, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9])

In [105]:
reverse_order = np.sort(arr7)[::-1]

In [106]:
reverse_order

array([[ 2,  2,  3,  4,  5,  7,  7,  8,  8,  8],
       [ 1,  1,  2,  3,  6,  6,  6,  8,  9, 10]])

In [107]:
arr1

array([1, 1, 1, 2, 2, 3, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9])

In [108]:
np.sort(arr1)[::-1]

array([9, 8, 8, 8, 8, 7, 7, 6, 6, 6, 5, 5, 5, 4, 3, 2, 2, 1, 1, 1])

In [109]:
a1= ([1,2,3])
a2= ([4,5,6])
a3 = ([7,8,9])

In [110]:
np.vstack ((a1,a2,a3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.hstack((a1,a2,a3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
arr2.shape

(4, 5)

In [114]:
arr2

array([[ 2, 10,  6,  3,  8],
       [ 6,  6,  9,  1,  1],
       [ 8,  7,  7,  4,  3],
       [ 2,  5,  8,  2,  8]])

In [116]:
arr9=np.transpose(arr2)

In [117]:
arr9.shape

(5, 4)

In [118]:
arr9

array([[ 2,  6,  8,  2],
       [10,  6,  7,  5],
       [ 6,  9,  7,  8],
       [ 3,  1,  4,  2],
       [ 8,  1,  3,  8]])

In [124]:
a1= ([1,2,3])
a2= ([4,5,6])
a3 = ([7,8,9])

In [127]:
np.column_stack((a1,a2,a3))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [130]:
#calling a function from differnet dircory

import sys
sys.path.append("path")
from volume import sphere

In [131]:
sphere(2)

33.49333333333333